@extends('layouts.app')

@section('content')
<!-- Calendar (replacing Upcoming Assignments) -->
<div class="card shadow-sm mb-4">
    <div class="card-header bg-white d-flex justify-content-between align-items-center">
        <h5 class="mb-0">Academic Calendar</h5>
        <div>
            <button id="prev-month" class="btn btn-sm btn-outline-secondary me-1"><i
                    class="fas fa-chevron-left"></i></button>
            <span id="current-month-display">{{ date('F Y') }}</span>
            <button id="next-month" class="btn btn-sm btn-outline-secondary ms-1"><i
                    class="fas fa-chevron-right"></i></button>
        </div>
    </div>
    <div class="card-body">
        <div id="calendar-container">
            <table class="table table-bordered calendar-table">
                <thead>
                    <tr>
                        <th>Sun</th>
                        <th>Mon</th>
                        <th>Tue</th>
                        <th>Wed</th>
                        <th>Thu</th>
                        <th>Fri</th>
                        <th>Sat</th>
                    </tr>
                </thead>
                <tbody id="calendar-body">
                    <!-- Calendar will be generated by JavaScript -->
                </tbody>
            </table>
        </div>
    </div>
</div>






<!-- Event Modal -->
<div class="modal fade" id="eventModal" tabindex="-1" aria-labelledby="eventModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header" style="background-color: #800000; color: white;">
                <h5 class="modal-title" id="eventModalLabel" style='color:white !important'>Event Details</h5>
                {{-- <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                --}}
                <!-- 👇 This is the close icon/button -->
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">x</button>
            </div>
            <div class="modal-body">
                <h4 id="event-title"></h4>
                <p><strong>Date: </strong><span id="event-date"></span></p>
                <div id="event-details"></div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal"
                    style='color:maroon;'>Close</button>
            </div>
        </div>
    </div>
</div>

<!-- Include jQuery, Bootstrap, and DataTables -->
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://cdn.datatables.net/1.13.1/js/jquery.dataTables.min.js"></script>

<!-- Pass Laravel Events to JS -->
<script>
    const events = @json($events);
</script>

<!-- Calendar Script with Modal -->
<script>
    const calendarBody = document.getElementById("calendar-body");
    const monthDisplay = document.getElementById("current-month-display");
    let currentDate = new Date();
    const eventModal = new bootstrap.Modal(document.getElementById('eventModal'));

    function renderCalendar(date) {
        const year = date.getFullYear();
        const month = date.getMonth();

        const firstDay = new Date(year, month, 1).getDay();
        const daysInMonth = new Date(year, month + 1, 0).getDate();

        calendarBody.innerHTML = "";

        let dateNum = 1;
        for (let i = 0; i < 6; i++) {
            const row = document.createElement("tr");

            for (let j = 0; j < 7; j++) {
                const cell = document.createElement("td");
                if (i === 0 && j < firstDay) {
                    cell.innerHTML = "";
                } else if (dateNum > daysInMonth) {
                    break;
                } else {
                    const cellDate = new Date(year, month, dateNum);
                    const formattedDate = cellDate.toISOString().split('T')[0];

                    const eventMatch = events.find(event => event.start_date === formattedDate);

                    if (eventMatch) {
                        // Just highlight the date without showing the title
                        cell.innerHTML = `<span class="badge bg-maroon event-date" data-event-id="${eventMatch.id}">${dateNum}</span>`;
                        cell.classList.add("event-cell");
                        
                        // Add click event to show modal
                        cell.addEventListener('click', function() {
                            document.getElementById('event-title').innerText = eventMatch.title;
                            document.getElementById('event-date').innerText = new Date(formattedDate).toLocaleDateString('en-US', { 
                                weekday: 'long', 
                                year: 'numeric', 
                                month: 'long', 
                                day: 'numeric' 
                            });
                            document.getElementById('event-details').innerText = eventMatch.description || 'No additional details available.';
                            eventModal.show();
                        });
                    } else {
                        cell.innerText = dateNum;
                    }

                    dateNum++;
                }
                row.appendChild(cell);
            }

            calendarBody.appendChild(row);
        }

        monthDisplay.innerText = date.toLocaleString('default', { month: 'long', year: 'numeric' });
    }

    document.getElementById("prev-month").addEventListener("click", () => {
        currentDate.setMonth(currentDate.getMonth() - 1);
        renderCalendar(currentDate);
    });

    document.getElementById("next-month").addEventListener("click", () => {
        currentDate.setMonth(currentDate.getMonth() + 1);
        renderCalendar(currentDate);
    });

    renderCalendar(currentDate);
</script>

<!-- Styling for Calendar and Events -->
<style>
    .bg-maroon {
        background-color: #800000 !important;
        color: white;
        padding: 5px 8px;
        border-radius: 50%;
    }

    .event-cell {
        cursor: pointer;
        position: relative;
    }

    .event-cell:hover {
        background-color: #f8f9fa;
    }

    .event-date {
        display: inline-block;
        transition: transform 0.2s;
    }

    .event-cell:hover .event-date {
        transform: scale(1.2);
    }
</style>
@endsection